### ISSUE TITLE
videos with odd width

### ISSUE THREAD

**Issue by dbath** [loopbio/stitchup#3] opened 2018-12-05 14:07 UTC
The image shape reported in metadata is different from the image shape from the resulting numpy arrays (see below). 

In [4]: store = imgstore.new_for_filename('/media/recnodes/recnode_2mfish/revers
   ...: als3m_64_dotbot_20181112_145201.stitched/metadata.yaml' )

In [5]: store.image_shape
Out[5]: (4049, 3866, 3)

In [6]: img, (_,_) = store.get_next_image()

In [7]: img.shape
Out[7]: (4048, 3866, 3)

**Comment by nzjrs** [comment] 2018-12-06 09:24
duplicate of https://github.com/loopbio/imgstore/issues/12

**Closed as completed by nzjrs** 2018-12-06 09:24 UTC

**Comment by nzjrs** [comment] 2018-12-06 09:25
@dbath can you please upload attach to the bug (maybe you need to rename it as metadata.yaml.txt) 
one of the metadata.yaml files from your broken stores?

I'll add it as a test case

**Comment by dbath** [comment] 2019-02-04 11:43
'/media/recnodes/recnode_2mfish/reversals3m_64_dotbot_20181112_145201.stitched/metadata.yaml'

**Comment by dbath** [comment] 2019-02-04 11:45
this problem occurs for all files in recnode_2mfish/*.stitched/metadata.yaml

**Comment by nzjrs** [comment] 2019-02-04 11:50
Thanks. For now you can work around this by doing the following

```python
maybe_broken_shape = store.image_shape

good_shape = list(maybe_broken_shape)
# bitwise and with -2 truncates downwards to even
good_shape[0] = int(good_shape[0]) & -2
good_shape[1] = int(good_shape[1]) & -2
```

and then use good_shape in your code

**Comment by nzjrs** [comment] 2019-02-08 12:54
@dbath  I made a new release of imgstore (0.2.3) which should fix this
